In [ ]:

import numpy as np
import torch
from PIL import Image
import imagenet_classes
from IPython.display import display

torch.backends.cuda.matmul.allow_tf32 = True
torch.manual_seed(0)

config = demo_util.get_config("configs/titok_l32.yaml")


titok_tokenizer = demo_util.get_titok_tokenizer(config)

In [5]:
from modeling.titok import TiTok
import demo_util
import torch
config = demo_util.get_config("configs/titok_vae_large.yaml")
tokenizer = TiTok(config)
state_dict = torch.load(config.experiment.tokenizer_checkpoint, map_location="cpu")

tokenizer.load_state_dict(state_dict, strict=False)


/private/task/jwn/anaconda3/envs/1D_tokeniser/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/private/task/jwn/anaconda3/envs/1D_tokeniser/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


loaded pretrained LPIPS loss from modules/lpips/vgg.pth
VQLPIPSWithDiscriminator running with hinge loss.


_IncompatibleKeys(missing_keys=['loss.perceptual_loss.scaling_layer.shift', 'loss.perceptual_loss.scaling_layer.scale', 'loss.perceptual_loss.net.slice1.0.weight', 'loss.perceptual_loss.net.slice1.0.bias', 'loss.perceptual_loss.net.slice1.2.weight', 'loss.perceptual_loss.net.slice1.2.bias', 'loss.perceptual_loss.net.slice2.5.weight', 'loss.perceptual_loss.net.slice2.5.bias', 'loss.perceptual_loss.net.slice2.7.weight', 'loss.perceptual_loss.net.slice2.7.bias', 'loss.perceptual_loss.net.slice3.10.weight', 'loss.perceptual_loss.net.slice3.10.bias', 'loss.perceptual_loss.net.slice3.12.weight', 'loss.perceptual_loss.net.slice3.12.bias', 'loss.perceptual_loss.net.slice3.14.weight', 'loss.perceptual_loss.net.slice3.14.bias', 'loss.perceptual_loss.net.slice4.17.weight', 'loss.perceptual_loss.net.slice4.17.bias', 'loss.perceptual_loss.net.slice4.19.weight', 'loss.perceptual_loss.net.slice4.19.bias', 'loss.perceptual_loss.net.slice4.21.weight', 'loss.perceptual_loss.net.slice4.21.bias', 'loss.pe

In [7]:
state_dict2 = torch.load("results/012-large/checkpoints/0030000.pt", map_location="cpu")

In [13]:
state_dict['encoder.transformer.0.ln_1.weight']

tensor([0.2005, 0.1701, 0.1526,  ..., 0.2194, 0.1003, 0.2167])

In [15]:
state_dict2["model"]['module.encoder.transformer.0.ln_1.weight']

tensor([0.2005, 0.1701, 0.1526,  ..., 0.2194, 0.1003, 0.2167])

In [21]:
tokenizer.encoder.transformer[0].ln_1.weight

Parameter containing:
tensor([0.2005, 0.1701, 0.1526,  ..., 0.2194, 0.1003, 0.2167],
       requires_grad=True)